yolo_model: "/workspace/jhlee/test/ultralytics-8.3.3/runs/detect/train54/weights/best.engine"
reid_model: "clip_vehicleid.pt"
tracking_method: "bytetrack"
track_thresh: 0.45
match_thresh: 0.8
track_buffer: 25
frame_rate: 30
per_class: False
source: "/workspace/jhlee/dataset/sbl/test/inside_test.mp4"
imgsz: 1280
conf: 0.25
iou: 0.7
half: True
per_class: False
device: [0]
stream: True
show: False
save: False
classes: [0,1,2,3,4,5,6,7,8,9]
project: "runs/"
name: "predict"
show_conf: True
show_trajectories: True
show_labels: True
agnostic_nms: False
save_txt: False
verbose: True
exist_ok: True
vid_stride: 1
line_width: 1